 name:  "Terraform"

 on: [push]
 env: 
    AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY}}

 jobs:
  terraform:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2-
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - name: terraform init
        run: terraform init
      - name: validate
        run: terraform validate
      - name: format
        run: terraform fmt -check
      - name: plan
        run: terraform plan   
